### **FinanceX**: Data Understanding

In [2]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
# load dataset
df = pd.read_csv(r'C:\Users\shali\OneDrive\Desktop\FinanceX\data\transactions.csv')

In [4]:
# print
df.head()

,transaction_id,customer_id,transaction_date,transaction_time,account_type,transaction_type,transaction_amount,transaction_direction,account_balance,merchant_category,state,credit_score,has_loan,loan_type,emi_amount,transaction_status,channel,kyc_status,is_fraud,transaction_hour
0,TXN000000001,CUST015796,2019-01-01,15:28,Current,UPI,1820.17,Debit,609365.31,Food & Dining,Maharashtra,764,0,NaN,0.00,Success,Branch,Verified,0,15
1,TXN000000002,CUST000861,2019-01-01,03:00,Current,UPI,392.67,Credit,14451.14,Education,West Bengal,630,0,NaN,0.00,Success,Mobile_App,Verified,0,3
2,TXN000000003,CUST076821,2019-01-01,18:03,Fixed Deposit,POS,1255.97,Debit,47621.87,Utilities,Punjab,813,1,Home,1433.91,Success,Mobile_App,Verified,0,18
3,TXN000000004,CUST054887,2019-01-01,08:03,Savings,UPI,2580.68,Debit,34467.85,Travel,Karnataka,628,1,Personal,6280.35,Success,API,Verified,0,8
4,TXN000000005,CUST006266,2019-01-01,14:23,Fixed Deposit,UPI,2573.80,Debit,26617.40,Utilities,West Bengal,767,0,NaN,0.00,Success,API,Verified,0,14

In [5]:
# drop useless coloumn
DROP_COLUMNS = [
    "transaction_id",
    "transaction_time",
    "transaction_type",
    "state",
    "credit_score",
    "has_loan",
    "loan_type",
    "kyc_status",
    "is_fraud"
]

df.drop(DROP_COLUMNS, axis=1, inplace=True)

In [6]:
df.head()

,customer_id,transaction_date,account_type,transaction_amount,transaction_direction,account_balance,merchant_category,emi_amount,transaction_status,channel,transaction_hour
0,CUST015796,2019-01-01,Current,1820.17,Debit,609365.31,Food & Dining,0.00,Success,Branch,15
1,CUST000861,2019-01-01,Current,392.67,Credit,14451.14,Education,0.00,Success,Mobile_App,3
2,CUST076821,2019-01-01,Fixed Deposit,1255.97,Debit,47621.87,Utilities,1433.91,Success,Mobile_App,18
3,CUST054887,2019-01-01,Savings,2580.68,Debit,34467.85,Travel,6280.35,Success,API,8
4,CUST006266,2019-01-01,Fixed Deposit,2573.80,Debit,26617.40,Utilities,0.00,Success,API,14

In [7]:
df.describe()

       transaction_amount  account_balance     emi_amount  transaction_hour
count        5.500000e+05     5.500000e+05  550000.000000     550000.000000
mean         2.990709e+04     8.455012e+04    2365.859974         11.504431
std          1.396101e+05     1.709146e+05    4973.546080          6.924499
min          2.400000e+00     5.000000e+02       0.000000          0.000000
25%          7.630375e+02     1.515778e+04       0.000000          6.000000
50%          2.035735e+03     3.642287e+04       0.000000         11.000000
75%          8.557497e+03     8.760704e+04    3115.030000         17.000000
max          1.000000e+07     5.000000e+06  153325.740000         23.000000

In [8]:
# check median 
df.median(numeric_only=True)

transaction_amount     2035.735
account_balance       36422.870
emi_amount                0.000
transaction_hour         11.000
dtype: float64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550000 entries, 0 to 549999
Data columns (total 11 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   customer_id            550000 non-null  object
 1   transaction_date       550000 non-null  object
 2   account_type           550000 non-null  object
 3   transaction_amount     550000 non-null  float64
 4   transaction_direction  550000 non-null  object
 5   account_balance        550000 non-null  float64
 6   merchant_category      550000 non-null  object
 7   emi_amount             550000 non-null  float64
 8   transaction_status     550000 non-null  object
 9   channel                550000 non-null  object
 10  transaction_hour       550000 non-null  int64
dtypes: float64(3), int64(1), object(7)
memory usage: 46.2+ MB

In [10]:
# check null values
df.isnull().sum()

# no null

customer_id              0
transaction_date         0
account_type             0
transaction_amount       0
transaction_direction    0
account_balance          0
merchant_category        0
emi_amount               0
transaction_status       0
channel                  0
transaction_hour         0
dtype: int64

In [11]:
# check dublicate values
df.duplicated().sum()

# no dublicate values

np.int64(0)

#### Outliers Observ

In [12]:
for col in ["transaction_amount", "account_balance", "emi_amount"]:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    count = ((df[col] < lower_bound) | (df[col] > upper_bound)).sum()

    print(f"{col}")
    print("Lower:", lower_bound)
    print("Upper:", upper_bound)
    print("Outliers:", count)
    print()

transaction_amount
Lower: -10928.652499999998
Upper: 20249.1875
Outliers: 88976

account_balance
Lower: -93516.09
Upper: 196280.91
Outliers: 53567

emi_amount
Lower: -4672.545
Upper: 7787.575000000001
Outliers: 54281

In [13]:
df[[
    "transaction_amount",
    "account_balance",
    "emi_amount"
]].describe().T

,count,mean,std,min,25%,50%,75%,max
transaction_amount,550000.0,29907.093934,139610.096520,2.4,763.0375,2035.735,8557.4975,10000000.00
account_balance,550000.0,84550.115076,170914.586239,500.0,15157.7850,36422.870,87607.0350,5000000.00
emi_amount,550000.0,2365.859974,4973.546080,0.0,0.0000,0.000,3115.0300,153325.74

In [14]:
print("Negative transaction amounts:",
      (df["transaction_amount"] < 0).sum())

print("Negative account balances:",
      (df["account_balance"] < 0).sum())

print("Negative EMI amounts:",
      (df["emi_amount"] < 0).sum())

Negative transaction amounts: 0
Negative account balances: 0
Negative EMI amounts: 0

In [15]:
print("Top transaction amounts:")
print(df["transaction_amount"].nlargest(20).to_list())

print("\nTop account balances:")
print(df["account_balance"].nlargest(20).to_list())

print("\nTop EMI amounts:")
print(df["emi_amount"].nlargest(20).to_list())

Top transaction amounts:
[10000000.0, 10000000.0, 10000000.0, 10000000.0, 9236223.15, 8480487.27, 8455419.74, 8009499.04, 7923295.55, 7899297.23, 7778436.54, 7698537.27, 7496971.32, 7491586.39, 7345022.23, 7187119.16, 7175579.82, 6751663.36, 6510670.17, 6443708.31]

Top account balances:
[5000000.0, 5000000.0, 5000000.0, 5000000.0, 5000000.0, 5000000.0, 5000000.0, 5000000.0, 5000000.0, 5000000.0, 5000000.0, 5000000.0, 5000000.0, 5000000.0, 5000000.0, 5000000.0, 5000000.0, 5000000.0, 5000000.0, 5000000.0]

Top EMI amounts:
[153325.74, 137161.99, 126816.9, 121942.95, 117391.88, 116235.61, 114971.97, 112464.0, 112332.26, 109682.04, 108095.25, 105520.5, 105473.72, 104521.02, 100643.52, 99801.23, 99721.33, 96319.89, 95655.53, 94637.35]

Outlier Analysis:
- transaction_amount, account_balance and emi_amount show strong right-skewed distributions.
- IQR method identifies a large number of statistical outliers.
- These observations are not removed at this stage because extreme financial values may represent legitimate transactions.
- Further validation is required before deciding whether any values are erroneous.
- transaction_hour appears to have a valid 0–24 range.

___

In [17]:
# df.to_csv(r'C:\Users\shali\OneDrive\Desktop\FinanceX\data\FinanceX_transaction.csv', index=False)