### **Data Cleaning**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r'C:\Users\shali\OneDrive\Desktop\FinanceX\data\FinanceX_transaction.csv')

In [8]:
df.head()

,customer_id,transaction_date,account_type,transaction_amount,transaction_direction,account_balance,merchant_category,emi_amount,transaction_status,channel,transaction_hour
0,CUST015796,2019-01-01,Current,1820.17,Debit,609365.31,Food & Dining,0.00,Success,Branch,15
1,CUST000861,2019-01-01,Current,392.67,Credit,14451.14,Education,0.00,Success,Mobile_App,3
2,CUST076821,2019-01-01,Fixed Deposit,1255.97,Debit,47621.87,Utilities,1433.91,Success,Mobile_App,18
3,CUST054887,2019-01-01,Savings,2580.68,Debit,34467.85,Travel,6280.35,Success,API,8
4,CUST006266,2019-01-01,Fixed Deposit,2573.80,Debit,26617.40,Utilities,0.00,Success,API,14

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550000 entries, 0 to 549999
Data columns (total 11 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   customer_id            550000 non-null  object
 1   transaction_date       550000 non-null  datetime64[ns]
 2   account_type           550000 non-null  object
 3   transaction_amount     550000 non-null  float64
 4   transaction_direction  550000 non-null  object
 5   account_balance        550000 non-null  float64
 6   merchant_category      550000 non-null  object
 7   emi_amount             550000 non-null  float64
 8   transaction_status     550000 non-null  object
 9   channel                550000 non-null  object
 10  transaction_hour       550000 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(1), object(6)
memory usage: 46.2+ MB

In [6]:
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

In [24]:
cat_col = df.select_dtypes(include='object').columns[1:]

for col in cat_col:
    print(df[col].value_counts())
    print("\n")

account_type
Savings          219651
Current          137648
Salary           110067
NRI               43746
Fixed Deposit     38888
Name: count, dtype: int64


transaction_direction
Debit     370394
Credit    179606
Name: count, dtype: int64


merchant_category
Retail           66180
Food & Dining    54776
E-Commerce       54767
Travel           44177
Salary           43937
Peer Transfer    38753
Utilities        38575
Healthcare       33015
Entertainment    32997
Government       27508
Investment       27380
Education        27359
Insurance        22020
Fuel             21929
Real Estate      16627
Name: count, dtype: int64


transaction_status
Success     506247
Failed       21905
Reversed     11019
Pending      10829
Name: count, dtype: int64


channel
Mobile_App      208368
Web             121010
ATM              66177
POS_Terminal     60853
Branch           54957
API              38635
Name: count, dtype: int64

In [26]:
df.groupby("transaction_status")["transaction_amount"].agg(
    ["count", "sum", "mean", "min", "max"]
)

                     count           sum          mean    min          max
transaction_status
Failed               21905  6.968504e+08  31812.391861   8.79   6130014.55
Pending              10829  3.344983e+08  30889.122973  13.20   8009499.04
Reversed             11019  3.257559e+08  29563.107819  10.31   3560643.30
Success             506247  1.509180e+10  29811.133739   2.40  10000000.00

In [27]:
df['transaction_direction'].value_counts()

transaction_direction
Debit     370394
Credit    179606
Name: count, dtype: int64

In [28]:
pd.crosstab(
    df["transaction_status"],
    df["transaction_direction"]
)

transaction_direction  Credit   Debit
transaction_status
Failed                   7096   14809
Pending                  3553    7276
Reversed                 3621    7398
Success                165336  340911

In [29]:
df.groupby("transaction_direction")["transaction_amount"].describe()

,count,mean,std,min,25%,50%,75%,max
transaction_direction,,,,,,,,
Credit,179606.0,42625.274100,165102.331019,2.40,764.8275,3041.325,17269.7600,10000000.0
Debit,370394.0,23739.981435,124931.689395,2.41,762.1525,2000.000,5899.5275,10000000.0

In [30]:
df["transaction_hour"].value_counts().sort_index()

transaction_hour
0     22928
1     23017
2     22740
3     22886
4     23082
5     22514
6     22931
7     22982
8     23242
9     22659
10    23111
11    23062
12    22891
13    22700
14    22790
15    23054
16    22993
17    22966
18    22576
19    22830
20    23075
21    22847
22    22984
23    23140
Name: count, dtype: int64

- Missing values          → None 
- Duplicates              → None 
- Negative values         → None 
- Categorical inconsistency → None found 
- Transaction status      → Valid 
- Debit/Credit            → Valid 
- Transaction hour        → Valid (0–23)

___

In [33]:
df.to_csv(r'C:\Users\shali\OneDrive\Desktop\FinanceX\data\FinanceX_transaction.csv', index=False)