### predict unseen data

In [1]:
import joblib
import pandas as pd 
import numpy as np

In [2]:
model = joblib.load(r"C:\Users\shali\OneDrive\Desktop\FinanceX\model\FinanceX_claassification_model.pkl")

In [3]:
df = pd.read_csv(r"C:\Users\shali\OneDrive\Desktop\FinanceX\data\classification_unseen.data.csv")

In [5]:
df.head()

,Unnamed: 0,current_spending,days_elapsed,avg_daily_spending,income,previous_month_expense,days_remaining,projected_month_end_spending,monthly_budget,budget_usage_percentage,budget_remaining,category_spending,year,month
0,0,16192.578367,23,704.025146,22673.153421,18127.553688,8,21824.779539,16984.632337,95.336643,792.053970,7164.363114,2026,1
1,1,5140.842328,9,571.204703,23085.912942,19633.035428,19,15993.731686,22273.769359,23.080253,17132.927032,1799.116575,2026,2
2,2,8730.634623,17,513.566743,23338.677031,16012.699817,14,15920.569019,19289.885043,45.260169,10559.250419,4611.241826,2026,3
3,3,6949.762175,12,579.146848,24417.405309,16119.792873,18,17374.405437,20271.317399,34.283722,13321.555224,3052.745024,2026,4
4,4,3770.946956,7,538.706708,23102.776889,17486.574778,24,16699.907947,16655.856977,22.640366,12884.910021,1648.228205,2026,5

In [9]:
df.drop(columns=['Unnamed: 0'],inplace=True)

In [12]:
prediction = model.predict(df)
prediction_df = pd.DataFrame(prediction, columns=['predicted_expense'])
prediction_df

       predicted_expense
0                      1
1                      0
2                      0
3                      0
4                      0
...                  ...
29995                  0
29996                  0
29997                  0
29998                  0
29999                  0

[30000 rows x 1 columns]