### Model Training

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\shali\OneDrive\Desktop\FinanceX\data\regression_dataset.csv")

In [3]:
df.shape

(63600, 14)

In [94]:
df.head()

,previous_month_expense,3_month_avg_expense,6_month_avg_expense,monthly_income,monthly_savings,transaction_count,avg_transaction_amount,food_expense,shopping_expense,travel_expense,entertainment_expense,others_expense,expense_trend,next_month_expense
0,28044.87,27740.82,26833.23,40853.57,16130.35,29,852.52,9636.61,4465.57,2401.72,4742.98,3476.33,0.000500,23104.21
1,24723.21,26642.86,26833.58,42789.18,19684.96,24,962.68,8682.13,4160.77,1952.82,5102.89,3205.61,-0.045740,23334.16
2,23104.21,25290.77,26343.78,41946.66,18612.50,32,729.19,9347.38,4344.52,2289.33,4304.88,3048.06,-0.097677,23482.73
3,23334.16,23720.53,25730.68,40167.34,16684.61,32,733.84,8807.97,4717.77,2032.38,4827.25,3097.37,-0.029280,22130.56
4,23482.73,23307.03,24974.95,38036.55,15905.99,22,1005.93,8764.68,3872.28,1810.56,4653.91,3029.14,0.008120,22328.99

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63600 entries, 0 to 63599
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   previous_month_expense  63600 non-null  float64
 1   3_month_avg_expense     63600 non-null  float64
 2   6_month_avg_expense     63600 non-null  float64
 3   monthly_income          63600 non-null  float64
 4   monthly_savings         63600 non-null  float64
 5   transaction_count       63600 non-null  int64
 6   avg_transaction_amount  63600 non-null  float64
 7   food_expense            63600 non-null  float64
 8   shopping_expense        63600 non-null  float64
 9   travel_expense          63600 non-null  float64
 10  entertainment_expense   63600 non-null  float64
 11  others_expense          63600 non-null  float64
 12  expense_trend           63600 non-null  float64
 13  next_month_expense      63600 non-null  float64
dtypes: float64(13), int64(1)
memory usage: 6.8 MB

In [64]:
x = df.drop('next_month_expense',axis=1)
y = df['next_month_expense']

In [65]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

#### model pipeline

In [66]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [67]:
linear_model = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LinearRegression())
])

descision_tree_model = Pipeline([
    ('DecisonTree',DecisionTreeRegressor(max_depth=10,random_state=42))
])

Random_forest = Pipeline([
    ('RandomForest',RandomForestRegressor(n_estimators=100,max_depth=10,random_state=42))
])

XGboost = Pipeline([
    ('XGBOOST', XGBRegressor(n_estimators=100,max_depth=10,random_state=42))
])

GradientBoosting = Pipeline([
    ('GradinetBoosting',GradientBoostingRegressor(n_estimators=100,max_depth=10,random_state=42))
])

models = {
    'Linear Regression':linear_model,
    'Decision Tree':descision_tree_model,
    'Random Forest':Random_forest,
    'XGBoost':XGboost,
    'Gradient Boosting':GradientBoosting
}

In [68]:
results = []

for name , pipeline in models.items():
    pipeline.fit(x_train,y_train)

    y_train_pred = pipeline.predict(x_train)
    y_test_predict = pipeline.predict(x_test)

    train_mse = mean_squared_error(y_train,y_train_pred)
    test_mse = mean_squared_error(y_test,y_test_predict)

    train_mae = mean_absolute_error(y_train,y_train_pred)
    test_mae = mean_absolute_error(y_test,y_test_predict)

    train_r2 = r2_score(y_train,y_train_pred)
    test_r2 = r2_score(y_test,y_test_predict)

    results.append({
        'model':name,
        'train_mse':train_mse,
        'test_mse':test_mse,
        'train_mae':train_mae,
        'test_mae':test_mae,
        'train_r2':train_r2,
        'test_r2':test_r2
    })

In [69]:
result_df = pd.DataFrame(results)
result_df

,model,train_mse,test_mse,train_mae,test_mae,train_r2,test_r2
0,Linear Regression,5.937654e+06,6.035149e+06,1783.789445,1785.545200,0.964511,0.964957
1,Decision Tree,6.817266e+06,9.785546e+06,1951.016723,2251.312702,0.959254,0.943181
2,Random Forest,5.444199e+06,7.532946e+06,1773.833054,2010.040371,0.967461,0.956260
3,XGBoost,7.175357e+05,7.291651e+06,613.285569,1936.708996,0.995711,0.957661
4,Gradient Boosting,1.711022e+06,6.725732e+06,1015.330006,1856.792531,0.989773,0.960947

In [88]:
# select best model
best_model = models['Random Forest']
best_model

Pipeline(steps=[('RandomForest',
                 RandomForestRegressor(max_depth=10, random_state=42))])

In [ ]:
final_model = best_model

# import joblib
# joblib.dump(
#     final_model,
#     r"C:\Users\shali\OneDrive\Desktop\FinanceX\model\FinanceX_regression_model.pkl"
# )

['C:\\Users\\shali\\OneDrive\\Desktop\\FinanceX\\model\\FinanceX_regression_model.pkl']

#### Hyperameter tuning

In [80]:
y_pred = best_model.predict(x_test)

accuracy = r2_score(y_test,y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.9562602512545525

In [86]:
rf_params = {
    "RandomForest__n_estimators": [200, 300, 500, 700],
    "RandomForest__max_depth": [5, 8, 10, 15, 20, None],
    "RandomForest__min_samples_split": [2, 5, 10],
    "RandomForest__min_samples_leaf": [1, 2, 4, 8],
    "RandomForest__max_features": [0.6, 0.8, 1.0]
}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV, TimeSeriesSplit

tscv = TimeSeriesSplit(
    n_splits=5
)

search = RandomizedSearchCV(
    estimator=best_model,
    param_distributions=rf_params,
    n_iter=25,
    scoring="neg_mean_absolute_error",
    cv=tscv,
    n_jobs=-1,
    random_state=42,
    verbose=1,
    refit=True
)

search.fit(x_train, y_train)